name: _init
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  json_path: ^0.4.2
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  page_transition: ^2.0.9
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
